name: CI/CD

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Build - String Boot"
    runs-on: ubuntu-latest

    steps:
      - name: "[Git] Checkout repository"
        uses: actions/checkout@v2

      - name: "[Backend] Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "[Backend] Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: "[Backend] Make gradlew executable"
        run: chmod +x ./gradlew

      - name: "[Backend] Build with Gradle"
        run: ./gradlew build

      - name: "[Artifact] Upload"
        uses: actions/upload-artifact@v2
        with:
          name: sl-servers-backend
          path: build/libs/*.jar

  docker:
    name: "Publish - GitHub Packages"
    runs-on: ubuntu-latest
    needs: [ build ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: "[Git] Checkout repository"
        uses: actions/checkout@v2

      - name: "[Artifact] Download"
        uses: actions/download-artifact@v2
        with:
          name: sl-servers-backend
          path: build/libs

      - name: "[Docker] Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "[Docker] Extract metadata (tags, labels) for Docker"
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "[Docker] Build and push Docker image"
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
